import { JSDOM } from "jsdom";
import { readFileSync } from "fs";
const html = readFileSync("./index.html", "utf8");
const dom = new JSDOM(html, { url: "https://example.com/blitzwort/", runScripts: "dangerously", pretendToBeVisual: true });
const { window } = dom;
window.requestAnimationFrame = (cb) => setTimeout(cb, 0);
window.cancelAnimationFrame = (id) => clearTimeout(id);
delete window.storage;
const spoken = [];
window.speechSynthesis = { cancel: () => {}, getVoices: () => [], speak: (u) => spoken.push(u.text) };
window.SpeechSynthesisUtterance = function (t) { this.text = t; };
await new Promise((r) => setTimeout(r, 300));
const playBtn = [...window.document.querySelectorAll("button")].find((b) => b.textContent.trim() === "▶");
playBtn.dispatchEvent(new window.MouseEvent("click", { bubbles: true }));
await new Promise((r) => setTimeout(r, 600));
const flashSpan = [...window.document.querySelectorAll("span")].find((s) => /^[a-zA-ZäöüÄÖÜß]+$/.test(s.textContent.trim()));
const target = flashSpan.textContent.trim();
await new Promise((r) => setTimeout(r, 2700));
const allTiles = [...window.document.querySelectorAll("button")].filter((b) => b.className === "tile" || b.textContent.trim().length > 0);
const wrongTile = [...window.document.querySelectorAll("button")].find((b) => {
  const t = b.textContent.trim();
  return t.length > 0 && t !== target && /^[a-zA-ZäöüÄÖÜß]+$/.test(t);
});
console.log("target:", target, " wrong tile picked:", wrongTile.textContent.trim());
wrongTile.dispatchEvent(new window.MouseEvent("click", { bubbles: true }));
await new Promise((r) => setTimeout(r, 150));
console.log("spoken after WRONG tap:", JSON.stringify(spoken));
console.log("speaks the TARGET (not the wrong tile text) on a miss:", spoken.includes(target + "."));
process.exit(spoken.includes(target + ".") ? 0 : 1);
